name: warranty_keeper_web
description: Offline invoice manager with AI-powered warranty tracking for Web.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # --- REPLACEMENTS ---
  shared_preferences: ^2.2.2 # Replaces Hive for simple web storage
  image_picker_for_web: ^3.0.1 # Web-specific image picker
  js: ^0.6.5 # To communicate with JavaScript (Tesseract.js)
  universal_html: ^2.2.4 # To work with HTML elements and files
  
  # --- REMAINING COMPATIBLE PACKAGES ---
  intl: ^0.18.0
  path_provider: ^2.0.15 # Still useful for getting paths
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
